window.ROLLS_ARCHIVE = {
  "categories": [
    { "id": "portraits", "label": "Portraits" },
    { "id": "landscapes", "label": "Landscapes" },
    { "id": "macro", "label": "Macro / details" },
    { "id": "street", "label": "Street" },
    { "id": "architecture", "label": "Architecture" },
    { "id": "nature", "label": "Nature" },
    { "id": "still-life", "label": "Still life" },
    { "id": "abstract", "label": "Abstract" }
  ],
  "rolls": [
    {
      "id": "macedonsko",
      "name": "Macedónsko",
      "sortOrder": 2,
      "photos": [
        { "file": "000003", "categories": ["street"] },
        { "file": "000008", "categories": ["portraits", "street"] },
        { "file": "000009", "categories": ["architecture"] },
        { "file": "000012", "categories": ["nature"] },
        { "file": "000014", "categories": ["portraits"] },
        { "file": "000017", "categories": ["landscapes"] },
        { "file": "000019", "categories": ["architecture", "street"] },
        { "file": "000022", "categories": ["portraits"] },
        { "file": "000023", "categories": ["still-life"] },
        { "file": "000024", "categories": ["nature", "macro"] },
        { "file": "000025", "categories": ["street"] },
        { "file": "000027", "categories": ["architecture"] },
        { "file": "000029", "categories": ["landscapes"] },
        { "file": "000030", "categories": ["portraits"] },
        { "file": "000031", "categories": ["abstract"] },
        { "file": "000032", "categories": ["architecture"] },
        { "file": "000034", "categories": ["street", "portraits"] },
        { "file": "000035", "categories": ["nature"] },
        { "file": "000036", "categories": ["landscapes"] },
        { "file": "000037", "categories": ["architecture", "abstract"] },
        { "file": "000038", "categories": ["still-life"] },
        { "file": "000040", "categories": ["street"] },
        { "file": "000041", "categories": ["portraits"] },
        { "file": "000042", "categories": ["nature"] },
        { "file": "ajHejAjNie", "categories": ["portraits"] },
        { "file": "chal", "categories": ["architecture"] },
        { "file": "chalosi", "categories": ["portraits", "street"] },
        { "file": "cocaCola", "categories": ["still-life"] },
        { "file": "kostol", "categories": ["architecture"] },
        { "file": "kriz", "categories": ["macro", "still-life"] },
        { "file": "miestoCinu", "categories": ["street"] },
        { "file": "nasadat", "categories": ["portraits"] },
        { "file": "predZoo", "categories": ["street"] },
        { "file": "rdo", "categories": ["landscapes"] },
        { "file": "rdo2", "categories": ["nature", "macro"] },
        { "file": "tiene", "categories": ["abstract"] },
        { "file": "zadna", "categories": ["architecture"] }
      ]
    },
    {
      "id": "vianoce24",
      "name": "Vianoce 2024",
      "sortOrder": 1,
      "photos": [
        { "file": "000004", "categories": ["portraits"] },
        { "file": "000009", "categories": ["still-life"] },
        { "file": "000010", "categories": ["macro"] },
        { "file": "000011", "categories": ["portraits"] },
        { "file": "000012", "categories": ["still-life"] },
        { "file": "000014", "categories": ["portraits"] },
        { "file": "000017", "categories": ["portraits"] },
        { "file": "000018", "categories": ["still-life"] },
        { "file": "000021", "categories": ["macro"] },
        { "file": "000022", "categories": ["portraits"] },
        { "file": "000023", "categories": ["still-life"] },
        { "file": "000024", "categories": ["macro", "still-life"] },
        { "file": "000025", "categories": ["portraits"] },
        { "file": "000030", "categories": ["abstract"] },
        { "file": "000031", "categories": ["portraits"] },
        { "file": "000032", "categories": ["still-life"] },
        { "file": "000035", "categories": ["portraits"] },
        { "file": "000036", "categories": ["macro"] },
        { "file": "000039", "categories": ["still-life"] },
        { "file": "000040", "categories": ["portraits"] },
        { "file": "000041", "categories": ["still-life"] },
        { "file": "audionefil", "categories": ["still-life"] },
        { "file": "maja", "categories": ["portraits"] },
        { "file": "mamka", "categories": ["portraits"] },
        { "file": "markMen", "categories": ["portraits"] },
        { "file": "nakupci", "categories": ["street"] },
        { "file": "peknaFotka", "categories": ["portraits"] },
        { "file": "pripravy", "categories": ["still-life"] },
        { "file": "pripravy2", "categories": ["macro"] },
        { "file": "rodinna", "categories": ["portraits"] },
        { "file": "stromcek", "categories": ["still-life"] },
        { "file": "stromcek2", "categories": ["macro"] },
        { "file": "surooo", "categories": ["still-life"] },
        { "file": "talir", "categories": ["still-life", "macro"] },
        { "file": "zavislak", "categories": ["portraits"] }
      ]
    }
  ]
};
